[build-system]
requires = ["setuptools>=61,<85", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "martini-taster"
version = "0.1.2"
description = "Martini CG free energy partition coefficient calculations."
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "Luís Borges Araújo", email = "luis.borges@ens-lyon.fr"},
  { name = "Pablo Cardona Perez", email = "pablo.cardona_perez@ens-lyon.fr" }
]
dependencies = [
  "numpy>=1.20",
  "pandas>=1.0",
  "matplotlib>=3.5",
  "MDAnalysis>=2.0",
  "alchemlyb>=2.0",
  "tqdm>=4.60",
  "jax>=0.7.2"
]

[dependency-groups]
lint = ["ruff==0.16.7", "nbqa", "pre-commit"]
typecheck = ["mypy", "types-tqdm", "pandas-stubs"]
test = ["pytest", "alchemtest"]
docs = ["sphinx", "sphinx-design","pydata-sphinx-theme","numpydoc","myst-nb"]
all = [
      { include-group = "lint" },
      { include-group = "typecheck" },
      { include-group = "test" },
      { include-group = "docs" }
      ]

[project.optional-dependencies]
cuda = ["jax[cuda13]>=0.7.2"]
rocm = ["jax[rocm7-local]>=0.7.2"]

[tool.uv]
conflicts = [
    [
        { extra = "cuda" },
        { extra = "rocm" },
    ],
]

[tool.ruff]
target-version = "py310"

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["taster*"]

[tool.setuptools.package-data]
taster = ["data/**/*"]

[project.scripts]
taster = "taster.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]

[[tool.mypy.overrides]]
module = [
  "MDAnalysis",
  "alchemlyb",
  "alchemlyb.convergence",
  "alchemlyb.estimators",
  "alchemlyb.parsing.gmx",
  "alchemlyb.visualisation"
]
ignore_missing_imports = true
