[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "taster"
version = "0.1.0"
description = "Martini CG free energy partition coefficient calculations."
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Luís Borges Araújo", email = "you@example.com" }]

dependencies = [
  "numpy>=1.20",
  "pandas>=1.0",
  "matplotlib>=3.5",
  "MDAnalysis>=2.0",
  "alchemlyb>=2.0",
  "tqdm>=4.60",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
]
docs = [
  "sphinx",
  "numpydoc",
  "myst-nb",
  "sphinx-design",
  "pydata-sphinx-theme",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["taster*"]

[tool.setuptools.package-data]
taster = ["data/**/*"]

[project.scripts]
taster = "taster.cli:main"